name

simple_shell

Description

     Shell is a program that verifies if the characters entered are created commands or are found in the machine, this verification is generated by the path. 

existing commands

- ls 
- ls -l
- ls -a
- pwd

commands created

- env 
- exit

SYNOPSYS
        
- #holbies$ env
Prints the envieron.

- #holbies$ exit
exit program

- #holbies$ ls -l
print list files or directories

- #holbies$ pwd 
prints the current route

- #holbies$ ls -a
prints the files or directories, including hidden ones. 

EXAMPLES

#holbies$ ls

AUTHORS        auxconcatenate.c  auxe.c           checkline.c  hsh        man_1_simpleshell  tokenizers.c

README.md      auxcopy.c         builtin.c        checkpath.c  ispath.c  pid.c
auxcompare.c  auxcounts.c       checkbuilt-in.c  getpath.c    main.h     shell.c


#holbies$ ls -l

total 92
-rw-r--r-- 1 maycolroa maycolroa   125 Dec  8 23:55 AUTHORS
-rw-r--r-- 1 maycolroa maycolroa  2171 Dec  8 23:51 README.md
-rw-r--r-- 1 maycolroa maycolroa   662 Dec  8 02:12 auxcompare.c
-rw-r--r-- 1 maycolroa maycolroa   320 Dec  8 02:20 auxconcatenate.c
-rw-r--r-- 1 maycolroa maycolroa   264 Dec  8 02:20 auxcopy.c
-rw-r--r-- 1 maycolroa maycolroa   191 Dec  8 02:24 auxcounts.c
-rw-r--r-- 1 maycolroa maycolroa   210 Dec  8 02:24 auxe.c
-rw-r--r-- 1 maycolroa maycolroa   613 Dec  8 02:29 builtin.c
-rw-r--r-- 1 maycolroa maycolroa   556 Dec  8 02:29 checkbuiltin.c
-rw-r--r-- 1 maycolroa maycolroa   338 Dec  8 02:34 checkline.c
-rw-r--r-- 1 maycolroa maycolroa   921 Dec  8 02:34 checkpath.c
-rw-r--r-- 1 maycolroa maycolroa   341 Dec  8 02:38 getpath.c
-rwxr-xr-x 1 maycolroa maycolroa 18304 Dec  9 05:32 hsh
-rw-r--r-- 1 maycolroa maycolroa   788 Dec  8 02:38 ispath.c
-rw-r--r-- 1 maycolroa maycolroa   894 Dec  8 14:35 main.h
-rw-r--r-- 1 maycolroa maycolroa  1974 Nov 29 21:16 man_1_simpleshell
-rw-r--r-- 1 maycolroa maycolroa   479 Dec  8 02:42 pid.c
-rw-r--r-- 1 maycolroa maycolroa   359 Dec  8 14:37 shell.c
-rw-r--r-- 1 maycolroa maycolroa   473 Dec  8 19:25 tokenizers.c

#holbies$ pwd

/home/maycolroa/holbertonschool/simple_shell

EXAMPLE OF ERROR

#holbies$ LS
LS: not found

#holbies$ cd
cd: not found

AUTHORS
* JACKSON MUENDO
* CHRISTINE CHEPKOECH
